import type { GlobeTheme } from './types';

export const THEMES: GlobeTheme[] = [
  {
    id: 'satellite',
    name: 'Satellite',
    description: 'Realistic Blue Marble satellite imagery with dark space background',
    earthTextureUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Blue_Marble_2002.png/1280px-Blue_Marble_2002.png',
    earthFallbackColor: 0x2233aa,
    backgroundColor: '#000011',
    ambientColor: 0xffffff,
    ambientIntensity: 0.5,
    directionalColor: 0xffffff,
    directionalIntensity: 1.0,
    gridColor: 0x4488ff,
    gridOpacity: 0.3,
    borderColor: 0x44aa88,
    borderOpacity: 0.4,
    markerScheme: 'default',
    showStarfield: true,
    roughness: 0.5,
    metalness: 0.1,
    atmosphereGlow: true,
    atmosphereColor: 0x4488ff,
    preview: 'Blue Marble satellite view with realistic lighting and atmosphere glow',
  },
  {
    id: 'dark',
    name: 'Dark Matter',
    description: 'Dark navy globe with cyan glowing borders and starfield',
    earthTextureUrl: null,
    earthFallbackColor: 0x0a0a2e,
    backgroundColor: '#000005',
    ambientColor: 0xffffff,
    ambientIntensity: 0.2,
    directionalColor: 0xffffff,
    directionalIntensity: 0.6,
    gridColor: 0x00ffcc,
    gridOpacity: 0.5,
    borderColor: 0x00ffcc,
    borderOpacity: 0.7,
    markerScheme: 'cool',
    showStarfield: true,
    starfieldColor: 0x00ffcc,
    roughness: 0.4,
    metalness: 0.3,
    atmosphereGlow: true,
    atmosphereColor: 0x00ffcc,
    preview: 'Dark navy procedural globe with neon cyan glow',
  },
  {
    id: 'topographic',
    name: 'Topographic',
    description: 'Elevation and terrain visualization',
    earthTextureUrl: 'https://unpkg.com/three-globe/example/img/earth-topology.png',
    earthFallbackColor: 0x8b7355,
    backgroundColor: '#1a1a2e',
    ambientColor: 0xffffff,
    ambientIntensity: 0.6,
    directionalColor: 0xffffff,
    directionalIntensity: 0.8,
    gridColor: 0x4488ff,
    gridOpacity: 0.3,
    borderColor: 0x665544,
    borderOpacity: 0.5,
    markerScheme: 'default',
    showStarfield: false,
    roughness: 0.8,
    metalness: 0.0,
    atmosphereGlow: false,
    preview: 'Topology-focused view with high roughness for terrain realism',
  },
  {
    id: 'night',
    name: 'Night Lights',
    description: 'City lights on dark earth with minimal ambient light',
    earthTextureUrl: 'https://unpkg.com/three-globe/example/img/earth-night.jpg',
    earthFallbackColor: 0x111122,
    backgroundColor: '#000000',
    ambientColor: 0xffffff,
    ambientIntensity: 0.15,
    directionalColor: 0xffffff,
    directionalIntensity: 0.3,
    gridColor: 0x333344,
    gridOpacity: 0.15,
    borderColor: 0x444466,
    borderOpacity: 0.3,
    markerScheme: 'default',
    showStarfield: true,
    roughness: 0.5,
    metalness: 0.1,
    atmosphereGlow: false,
    preview: 'Dark earth with city lights and subtle grid',
  },
  {
    id: 'wireframe',
    name: 'Wireframe',
    description: 'Geometric wireframe-style globe',
    earthTextureUrl: null,
    earthFallbackColor: 0x000000,
    backgroundColor: '#000011',
    ambientColor: 0xffffff,
    ambientIntensity: 0.4,
    directionalColor: 0xffffff,
    directionalIntensity: 0.7,
    gridColor: 0x00ff88,
    gridOpacity: 0.7,
    borderColor: 0x00ff88,
    borderOpacity: 0.7,
    markerScheme: 'cool',
    showStarfield: true,
    roughness: 0.3,
    metalness: 0.9,
    atmosphereGlow: false,
    preview: 'Dark sphere with bright green wireframe grid and borders',
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Clean, flat design with desaturated continents',
    earthTextureUrl: 'https://unpkg.com/three-globe/example/img/earth-blue-marble.jpg',
    earthFallbackColor: 0xcccccc,
    backgroundColor: '#e8e8e8',
    ambientColor: 0xffffff,
    ambientIntensity: 0.8,
    directionalColor: 0xffffff,
    directionalIntensity: 0.4,
    gridColor: 0x888888,
    gridOpacity: 0.1,
    borderColor: 0x666666,
    borderOpacity: 0.3,
    markerScheme: 'mono',
    showStarfield: false,
    roughness: 0.6,
    metalness: 0.0,
    atmosphereGlow: false,
    preview: 'Light background with desaturated blue marble',
  },
  {
    id: 'cartography',
    name: 'Cartography',
    description: 'Classic sepia-toned antique map aesthetic',
    earthTextureUrl: null,
    earthFallbackColor: 0xd4c5a9,
    backgroundColor: '#2c2416',
    ambientColor: 0xffeebb,
    ambientIntensity: 0.4,
    directionalColor: 0xffffff,
    directionalIntensity: 0.9,
    gridColor: 0x8b7355,
    gridOpacity: 0.2,
    borderColor: 0x5c4033,
    borderOpacity: 0.5,
    markerScheme: 'default',
    showStarfield: false,
    roughness: 0.7,
    metalness: 0.0,
    atmosphereGlow: false,
    preview: 'Antique sepia map with warm amber ambient light',
  },
  {
    id: 'inferno',
    name: 'Inferno',
    description: 'Volcanic and heat-focused dramatic theme',
    earthTextureUrl: null,
    earthFallbackColor: 0x1a0a00,
    backgroundColor: '#0a0000',
    ambientColor: 0xff4400,
    ambientIntensity: 0.3,
    directionalColor: 0xff6600,
    directionalIntensity: 1.2,
    gridColor: 0xff3300,
    gridOpacity: 0.2,
    borderColor: 0xff4400,
    borderOpacity: 0.3,
    markerScheme: 'hot',
    showStarfield: false,
    roughness: 0.5,
    metalness: 0.4,
    atmosphereGlow: true,
    atmosphereColor: 0xff3300,
    preview: 'Volcanic dark globe with fiery orange glow',
  },
];
